### ISSUE TITLE
Gnome 3.22 Activities Configurator breakage  

### ISSUE THREAD

**Issue by frague59** [nls1729/acme-code#12]
Hi, 
I've upgraded my gnome-shell to 3.22, and I've seen a breackage in Activities Configurator:
When I right-click on activities button, I can't manage my extensions anymore : a blank (unclosable) window appears...
Same from gnome-tweak-tool and click on settings button.
Thanks for those great extensions !

**Comment by nls1729** [comment]
Your problem is with the gnome-shell-extension-prefs tool.  It is a small C program that executes gjs javascript code to set extension preferences.  It is part of the gnome-shell package.  The Activities Configurator and the gnome-tweak-tool simply execute gnome-shell-extension-prefs.  I suspect something went wrong with your upgrade to Gnome Shell 3.22.  I am currently testing Fedora 25 alpha with Wayland and X11.  Fedora 25 alpha has Gnome Shell version 3.22.0.  I do not see any problems with the extension on 3.22 on Fedora 25 alpha.

Try running the prefs tool in a terminal session.

$ gnome-shell-extension-prefs

If you see any error messages it might indicate what is wrong with your upgrade.

I do not know of any linux distribution that provides supported 3.22 upgrades yet.  The last information I find is openSUSE nightly live images include 3.22 and Arch linux has it as an unstable package.  

In any case I suggest you report your problem to the source of your upgrade.  There is probably a wrong dependency version or missing component issue. 

Let me know how it goes.
