### ISSUE TITLE
could not make panel transparent

### ISSUE THREAD

**Issue by chetanpm** [nls1729/acme-code#19]
I tried all possible combinations in the activity configurator settings, still couldnot make the top bar transparent
![screenshot from 2016-12-06 12-33-58](https://cloud.githubusercontent.com/assets/9249405/20916282/f72fa052-bbb0-11e6-923e-2c07da8dd1c4.png)

**Comment by nls1729** [comment]
The appearance of the Gnome Shell desktop is controlled by a mechanism called CSS, cascading style sheet.  The Activities Configurator extension modifies some CSS elements provided by the Default shell theme.  When a user provided theme is installed depending on how and which elements in the user theme are different from the Default theme, the  Activities Configurator extension may or may NOT affect the desktop appearance.  In fact in order to not interfere with the user theme the extension detects when a user theme is installed and disables its settings that could affect elements changed by the user theme.  The extension enables the Override Shell Theme preference and sets it of OFF.  If the user wishes to use the extension’ s preferences setting the preference to ON enables the settings that could affect the user theme.

I installed and examined the Arc theme coding.  The Arc theme applies a background image to the top panel.  The extension cannot override this effect.  The image overlays the panel and changing  the color and transparency below the image is not effective.  If the Arc theme you have is the same as the Arc theme that I installed,  I have a possible workaround the you can try.  Users themes are installed in two possible locations,  in your home directory in .themes or in /usr/local/share/themes.

1. Find which directory where the Arc theme is installed.

$ ls  ~/.themes

If you see a sub-directory Arc, it is installed here.

$ ls /usr/local/share/themes

If you see a sub-directory Arc, it is installed here.

It is possible to have it installed in both places.

If it is installed in both places you can rename one of the Arc sub-directories to Arc2 to identify which is which.

2. In the sub-directory Arc/gnome-shell/common-assets/panel find the file panel.svg.  Rename panel.svg to panel.svgx.

3.  Set the extension preference Override Shell Theme [ Arc ] to ON.

This should fix your problem.  If it does not you may have an Arc theme different from the Arc theme I have installed.  

Let me know how it goes.  I will leave this issue open until I hear from you.

Regards,
Norman

**Comment by chetanpm** [comment]
Renamed to panel.svgx
now the Overide works :)

**Comment by chetanpm** [comment]
Although panel transparency is either full transparent or opaque. No other in-between values working.

**Comment by nls1729** [comment]
If you hold the mouse button down too long  on the +, the control will stack increments.  Press and release quickly one step at a time.  You can check the settings with dconf-editor. 
![image](https://cloud.githubusercontent.com/assets/2984166/20965102/4b8b5b32-bc42-11e6-9da6-2ee9613bf906.png)
With dconf-editor select org/gnome/shell/extensions/activities-config, find  "transparent-panel" on the right.
You can actually click on the value and change it or observe it as you click the mouse on the + of the preferences tool.

Let me know if that solves your problem.  I can set it to any value 0-100 with the Arc I have installed.  If it doesn't work for you, where did you get your copy of the Arc theme?

**Comment by chetanpm** [comment]
well, I used gnome-tweak-tool to change settings on the extensions.. as I mentioned, some settings wouldn't change there.


Checking with dconf-editor, I get this
![screenshot from 2016-12-07 19-18-38](https://cloud.githubusercontent.com/assets/9249405/20970249/a0a33e4e-bcb2-11e6-83bf-001b00739cfa.png)

**Comment by nls1729** [comment]
First the desktop effects are layered.  If with the Tweak tool under Tweaks you select Desktop and then under Background select  Mode  None, the entire Desktop background is black. This is layer 0.

If Mode Scaled is selected and depending upon the dimensions of the background image you may or may not see black bands at the top and bottom of the Desktop or on the sides.  The background image may not cover the entire Desktop background.  If  Mode  Stretched  is selected the background image will cover the entire Desktop background.  The Desktop background image is layer 1  whether it covers the entire image on not.

The Panel is at layer 2.  The extension affects the Panel background.  When we started the Arc theme was adding an image at what would be layer 3.  That blocked the effects of the extension and by renaming the image file we should be able to affect the Panel background color and transparency. 

In the first image below note that the Panel background color is yellow and the Panel transparency is 40.  The Desktop background image does not cover the area under the Panel  so we see a mix of yellow and black at a Panel background transparency of 40. 
![0](https://cloud.githubusercontent.com/assets/2984166/20980201/94fe7156-bc7d-11e6-814a-b27982586e11.jpg)

In the second image below the Desktop background image is Stretched and the gray image and the yellow Panel color are mixed to yield a purer yellow panel.
![1](https://cloud.githubusercontent.com/assets/2984166/20980261/d5fc07c2-bc7d-11e6-9c2e-780487ffa736.jpg)

In the third image you see the value of the transparent-panel preference.  Note the missing schema warning is not a problem.  A file for schema data is in your home directory, ~/.config/dconf/user, which includes extension schema data and system schema data.  If you remove the file it will be re-created as needed.
![2](https://cloud.githubusercontent.com/assets/2984166/20980327/17e52cf4-bc7e-11e6-8c4f-6eb4fc956c61.jpg)

The Panel background transparency and color preference work together.  From what I’ve seen in your images I think it is working but the Panel background color must be different from the color of the layer immediately below it.

Is this helpful?

**Comment by chetanpm** [comment]
That was comprehensive. I now understand the model well, I changed panel background color and got the exact look I wanted. You did explain every thing very patiently and that was enlightning :+1:  :)

**Comment by nls1729** [comment]
Closing this issue, live long and prosper...
