### ISSUE TITLE
Activities Configurator intermittently disables the "Hide panel rounded corners" option

### ISSUE THREAD

**Issue by jessedubord** [nls1729/acme-code#25]
BEHAVIOR
Though I can't specifically pinpoint when, occasionally the Activities Configurator will disable the "Hide panel rounded corners" option... yet when I go into the configuration settings window, the button is switched to on, not off.

EXPECTED BEHAVIOR
When the "Hide panel rounded corners" button is switched to yes, the rounded corners won't intermittently re-appear and have to be re-enabled and then re-disabled.

ISSUE DISCOVERED USING
Ubuntu (GNOME) 17.04 x64
Gnome 3.24.1 desktop environment
Linux kernel 4.10.0-21-generic

**Comment by nls1729** [comment]
During normal operation the Activities Configurator only hides or shows the rounded corners based on the preference setting at start-up or if the preference is changed manually.  You are finding the Hide Panel Rounded Corners setting in the ON position with the corners visible.  It appears something altered the visibility property of the corners.  It is likely another extension or other software is "showing" the corners.  About eighteen months ago a similar problem appeared and was caused by another extension. Our first step will be to attempt to find an offending extension.

Conflicts between extensions are the source of many bugs.  Extensions are actually monkey patched into the Gnome-Shell.  Since there is no co-ordination between extension writers patches can collide.  See https://en.wikipedia.org/wiki/Monkey_patch  Pitfalls.     
 
Please perform the following procedure. 

1. Pick an extension (not the Activities Configurator) and disable it. 
2. Watch for the problem.
3. If the problem occurs re-enable the selected extension.
4. Go to step 1 and repeat with a different extension.

If the problem does not occur with an extension disabled we have found the offender.  I can examine its code and may be able to find a way to workaround its behavior.

If the offender cannot be found there are other methods to root out the cause.

Thanks for your report.
Norman

**Comment by nls1729** [comment]
I found a case where the conflict detection and remediation code added 18 months ago will fail. I have added code to handle the failure case.  Please install the attached zip file.  Let me know if you continue to see the problem or find the problem has been cleared.

[activities-config@nls1729.zip](https://github.com/nls1729/acme-code/files/1065177/activities-config.nls1729.zip)

**Comment by nls1729** [comment]
Activities Configurator Version 56 is now available on the extension website.  Added additional hidden rounded corners defensive logic to re-hide corners if shown by another extension.

**Comment by jessedubord** [comment]
Confirmed fix, thank you!
