### ISSUE TITLE
Extension reloader does not load manually installed extension from disk.

### ISSUE THREAD

**Issue by Vaesper** [nls1729/acme-code#27]
### What I did:
1. Change an extension code on disk (manually installed - I `git checkout`-ed a different commit to hunt down a bug).
2. Reload the extension with GSER.

### What I expected to happen:
Extension to now be running the newly `checkout`-ed commit.

### What actually happened:
Extension still running the old commit.

**Comment by criztovyl** [comment]
I think this is not Extension Reloaders fault, last time I checked Gnome Shell itself was the problem.

Some links:
[extension-reloader/extension.js L110](https://github.com/nls1729/acme-code/blob/master/extension-reloader/extension.js#L110)
[gnome-shell/js/ui/extensionSystem.js L193](https://github.com/GNOME/gnome-shell/blob/master/js/ui/extensionSystem.js#L193)

**Comment by nls1729** [comment]
I think criztovyl  is correct.  It appears if the target extension is in the enabled state, the reload appears to succeed with no error, but the code on disk is not actually accessed by shell extension system.  If the extension is in the error state the code on disk is accessed and reloaded and will be enabled if the error state has been corrected.  I will take a look at the shell extension system code and see if I can find why the reload is not being done correctly.

**Comment by nls1729** [comment]
I found my comment above is not completely correct.  It depends on the extension and which files are changed.

This problem is very strange.  I used the window-list@gnome-shell-extensions.gcampax.github.com as a test case.  I changed the stylesheet.css file to set the width of the buttons to 4 characters wide.  I logged out and logged in and found the buttons to be 4 characters wide.  I added log messages at several points in the extension.js file.  I changed the stylesheet.css file to set the width of the buttons to 20 characters wide.  I reloaded window-list with the extension.  The log messages were found in the log.  The buttons remained at 4 characters wide.  I then logged out and logged in and found the buttons to be 20 characters wide.  It appears the extension was not completely re-created by the reload function in the extension system.

I repeated the above with a syntax error to cause the reload to fail.  I corrected the error and reloaded.
The results was the same.  The extension was not completely re-created.

The code on disk was definitely used to re-create the extension during the reload as shown by the log messages.  The buttons remaining the sames size indicates the stylesheet.css was not used during the reload.

Questions:
What version of Gnome Shell is installed on your system?
How do you know the code on the disk was not used during the reload?

Please re-create the problem with log functions in the init, enable and disable functions.
Check the log to confirm the extension.js file was or was not used to recreate the extension during the reload.

Let me know how it goes.

**Comment by nls1729** [comment]
I repeated tests running an X session and found the same behavior as running a Wayland session.  This leads me to the conclusion that the GSER extension has a limitation when the changes to the code affect the appearance of the GUI.  To see the change from 4 characters to 20 characters under X reguired an Alt F2 r session restart.  It seems a log out and re-login is required under Wayland if the extension code changes affect the appearance of the GUI.  I don't think a quick session restart will be implemented for Gnome Shell with Wayland.  The GSER extension is still useful for finding coding errors.  I will note the limitation on the extension website and in the readme for extension.

**Comment by njam** [comment]
I also experience the problem that reloading an extension doesn't re-read the JavaScript from the filesystem. It seems to be a known issue of gnome-shell:
https://bugzilla.gnome.org/show_bug.cgi?id=782187

**Comment by nls1729** [comment]
njam Thanks for your comment.  Now the only use of this extension is to reload if the extension is in the error state and a possible correction has been made to the code.
