### ISSUE TITLE
Do Not Disturb extension not working on 3.26

### ISSUE THREAD

**Issue by fgblomqvist** [nls1729/acme-code#32]
Notifications still pop up despite that I have busy-mode on.

**Comment by nls1729** [comment]
I did not receive a notification email of this issue.  I am currently trying to resolve the problem with not receiving emails.  I will look into your issue as soon as I can find the time.   Please note if a notification is designated as critical it will be displayed when the busy-mode is on.

**Comment by fgblomqvist** [comment]
I seem to be getting all notifications, so unless every single app marks them as critical something is wrong.

**Comment by nls1729** [comment]
Hello:
Please perform the following test.  You will need the notify-send application and the Gnome Tweak Tool.

1. With the Tweak tool disable all extensions except the Do Not Disturb Button.
2. Restart your Gnome Session by logout login.
3. Get a command prompt by starting Terminal.
4. Set the Do Not Disturb Button to not busy.
5. At the command prompt:
 notify-send "Hello World"
You should see the notification.
6. Set the Do Not Disturb Button to busy mode.
 notify-send "Hello World"
You should not see the notification.
If you do not see the notification one of the disabled extensions is causing the problem.
You can enable the extensions one at a time to find the offending extension.
If you see the message you may have an application that is causing the problem.
A likely candidate is a chat app.

Let me know how it goes...
Norman

**Comment by fgblomqvist** [comment]
Just did the test and you were correct, everything is working like it should. It just happens to be that the apps that I use all send critical notifications for some dumb reason. There should be a way to force-hide those as well (not sure if it's possible though).

**Comment by nls1729** [comment]
The urgency level of Critical cannot  be blocked .  To quote the Gnome specification, "They should only be closed when the user dismisses them...".  An application should only use the Critical urgency level for a serious matter where immediate attention is required.  An example of an instance where immediate attention is required is a file system about to run out of space.  You can't block critical notifications because some notifications are truly Critical.   If possible you may want to file a bug report on the offending apps.
