### ISSUE TITLE
Activities Configurator not working with Ubuntu 18.04 beta 2, Gnome 3.28

### ISSUE THREAD

**Issue by jessedubord** [nls1729/acme-code#34]
When I go into GNOME Tweaks and try to configure the Activities Configurator extension, a terminal opens up saying the following:
"There was an error loading the preferences dialog for Activities Configurator:"
Error: Requiring Clutter, version none: Typelib file for namespace 'Clutter' (any version) not found

Stack trace:
  @/home/jesse/.local/share/gnome-shell/extensions/activities-config@nls1729/colors.js:1:7
  @/home/jesse/.local/share/gnome-shell/extensions/activities-config@nls1729/prefs.js:15:7
  _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
  @<main>:1:43

Bug discovered using:
Ubuntu 18.04 beta 2
Gnome 3.28 (gnome-session, X.org -- not the Ubuntu default gnome session)
Linux kernel 4.15.0-13-generic

**Comment by nls1729** [comment]
Sometimes I don't get an email from Github when an issue is opened.  Most of the time I do.  Sorry about the late attention to your issue.   Either I missed the email or Github didn't send it.

Apparently you changed the metadata.json file to indicate GS version 3.28 and have loaded the extension.  Instead of using the Tweak tool please try clicking on the Activities Icon or Text displayed by the extension with the secondary (usually left) mouse button and let me know what happens.

**Comment by jessedubord** [comment]
No worries, appreciate the reply!
With the Activities Configurator extension enabled, left-clicking the "happy face" icon activates the Overview. Right-clicking the happy face icon opens the shell extensions window. I see Activities Configurator enabled, but clicking on the gear from within the shell extensions window bring up the same error as the original post.

**Comment by nls1729** [comment]
I have tested the extension on Gnome Shell 3.28 Xorg, Classic and Gnome sessions with Fedora 28 Beta.  I could not duplicate the bug you reported.  I use Fedora for testing because it is based on un-modified Gnome Shell code.  However; I went through the prefs.js code and found one line that is not needed and may have run into conflict with new Ubuntu shell modifications.  Please try the following:

Delete line 15 in the file prefs.js, "const Colors = Me.imports.colors;".  Restart your session and let me know if it clears your problem.

**Comment by jessedubord** [comment]
Sorry for the late reply. I deleted the line in the prefs.js file you mentioned (located in ~/.local/share/gnome-shell/extensions/activities-config@nls1729/) then re-enabled the extension, and was able to open the settings, successfully! Problem solved. :)

**Comment by nls1729** [comment]
I have uploaded a new version with the change to work with Unbuntu 18.04 LTS.  There is a long list of extensions in front of me waiting review.  I posted a comment on the ego website with the fix for anyone who runs into the problem before the updated extension is available. Thanks  for report.
