### ISSUE TITLE
donotdisturb-button: Suggestion: make click on icon persistent

### ISSUE THREAD

**Issue by hyphone** [nls1729/acme-code#36]
Hello and good day,

I'm that gnomemenow guy and want to describe what I mean about the click-behaviour here as you suggested.

The following is the stauts quo:
- preference "busy" (for me in german it's called "Beschäftigt") is not activated and I can be disturbed (because that's my default)
- I click the icon to the state "not get distrubed"
- I lock the screen
- I unlock the screen
- extension is now in the state "get disturbed" again

When I lock the screen I haven't changed my mind to "get distrubed" or "not get distrurbed" so I personally would prefer that the state after unlocking the screen should be the same as before I locked the screen.

Edit: added " to perhaps make it a little more clear
Edit2: we also could tilte this issue as "don't lose current state after suspend / screen lock / gnome-shell restart"
Edit3: changed the title to reflect the said extension

**Comment by nls1729** [comment]
Thanks for posting this issue.  I think I have an  acceptable solution to your issue.

The new Busy State Override At Session Start preference consists of an "Enable" checkbox, "Busy" radiobutton and "Avaliable" radiobutton.  If "Enable" is unchecked, the default is that the state of the extension panel icon controls the busy state in a persistent manner.  Whatever state the icon was in when the session ended or was interrupted by a screen lock or user switch determines the state at the next session login or re-login after a screen lock or user switch.  If the "Enable" is checked the state indicated by the selected radiobutton will only set the state at the next new session login; otherwise, the persistent behavior is in effect.  Some folks want to start with the busy state in effect at startup and some want to start with the available state in effect.  Hopefully this approach will satisfy everyone.  I am testing the code now.  I will post again when I finish testing with a link to a zip file you can download and verfiy it works to your liking.

Norman

**Comment by hyphone** [comment]
Thanks for having a look.

I'm looking forward for the new version :)

**Comment by nls1729** [comment]
The following tinyurl will allow you to download the extension zip and a zip of a tool you might want to use to install or uninstall extensions.  The tool's Makefile should work on most Gnome Shell linux distros.  The tinyurl provides a preview of the actual link to a folder on my Google drive.  I think you should always see the actual link of the tinyurl . 

https://preview.tinyurl.com/ybhd3pzc

I would appreciate a German translation of the following to update the extension.  
Busy State Override At Session Start
Enable
Available

Let me know if the changes are acceptable.
Norman

**Comment by hyphone** [comment]
Thank you very much Norman. This works great for me. When I now log in I receive notifications and when I decide not to it sticks until I want them again.

"Busy State Override At Session Start" -> "Beschäftigt-Status bei Session Start überschreiben"
enable / disable is already translated
