### ISSUE TITLE
Activities button on multiple desktops

### ISSUE THREAD

**Issue by Corben78** [nls1729/acme-code#43]
I upgraded from Ubuntu 16.04 to 18.04 and found this extension useful to have a nice Ubuntu logo instead of the "Activities" letters in the top left corner.
I'm also using the [multi monitors add-on](https://github.com/spin83/multi-monitors-add-on) extension, so I have the top panel on all monitors, as it was with Unity before.
Unfortunately there the "Activities" still remains and is not replaced by the configured logo.
Is there a way to replace "Activities" on the other monitors with the logo too?

**Comment by nls1729** [comment]
The Activities Button is a part of the top panel.  I looked at the multi monitor add-on extension code.  The multi monitor add-on extension is not compatible with the Activities Configurator.  The "Activities" text you are seeing is created by the  multi monitor add-on extension in panels that are used instead of the original shell code.  Gnome Shell extensions are actually patches to the shell code.  The last patch applied is what you get.

**Comment by Corben78** [comment]
Thanks for you reply.
Too bad the multi monitor add-on creates its own panels, that are not affected by the activities configurator. First I thought, the order in which the addons are installed does matter, but it didn't change anything.
I guess the multi monitor add-on isn't maintained any more, so I don't have high hopes it would be patched to become compatible with this addon.
