### ISSUE TITLE
After lockscreen, panel is transparent

### ISSUE THREAD

**Issue by Mipronimo** [nls1729/acme-code#46]
The configuration says the panel is only transparent, if no window is maximized. When I lock the screen and unlock it again, the panel is transparent, but the windows are maximized.

![bildschirmfoto von 2018-11-21 18-08-49](https://user-images.githubusercontent.com/35998229/48857231-a999e280-edb8-11e8-8f03-4582ab0f02a7.png)Sorry, that the screenshot is in German, but you should be able to know, what the settings mean in English (:

_[v67 GS 3.28,3.30]_
_Gnome Shell: 3.30.1_

Thanks a lot

**Comment by nls1729** [comment]
@Mipronimo 

You are correct.  The panel should not be transparent. The panel should be opaque background color.  I have attached an updated file  in extension.zip. Please extract  extension.js from extension.zip. Then
remove the file extension.js in the activities-config@nls1729 directory and replace it with the extracted file.  Restart the gnome-shell session (log out then login). Please check the extension behavior when logging in from a locked screen. Let me know if the fix is OK.  I will upload an updated extension to extensions.gnome.org when I get your OK.

[extension.zip](https://github.com/nls1729/acme-code/files/2609049/extension.zip)

If you have any questions please comment here.
Thanks for reporting this issue.
Norman

**Comment by Mipronimo** [comment]
@nls1729 

This is working fine. Thanks!

**Comment by nls1729** [comment]
@Mipronimo 
FYI
Activities Configurator,  v68 passed review and is now available on extensions.gnome.org.
Thanks again for reporting this issue.
