### ISSUE TITLE
Does not work with Gnome 3.321 

### ISSUE THREAD

**Issue by lsatenstein** [nls1729/acme-code#48]
Sadly, Gnome is still an interface that is in constant development.  
Your program works with Fedora29 but fails with Rawhide (the next gnome version)
Rawhide may be at 3.22  Gnome is ashamed to indicate the version anywhere in the Gnome Fedora interfaces.

**Comment by nls1729** [comment]
Fedora 29 is currently on 3.30.2
$ uname -r
4.19.5-300.fc29.x86_64
$ gnome-shell --version
GNOME Shell 3.30.2
Rawhide is not stable.  It is not suitable for normal use.  You can't use it to test Gnome Shell extensions.  The problem you experienced is probably with my extension, but I have found it is a waste of time to try to find a problem before there is at least a beta version of a linux distribution available for testing.  I prefer Fedora because they usually have a beta not long after a new Gnome Shell version is released.   I always test with a beta as soon as they are available.  In a linux distribution there too many things that are dependent upon each other to update from a testing repo like rawhide.

**Comment by nls1729** [comment]
There is no 3.321 Gnome available. See https://wiki.gnome.org/ThreePointThirtyone for the release schedule for the development releases 3.21.x and the production releases 3.32.x.  Using rawhide can cause problems.  Closing this issue.
