### ISSUE TITLE
Do Not Disturb: Timeout feature

### ISSUE THREAD

**Issue by bostrt** [nls1729/acme-code#49]
Is it possible to add a timeout feature that automatically drops you out of do-not-disturb?

**Comment by nls1729** [comment]
I only add new features to the lastest version of the
extension because the gnome shell is a moving target.
If you are using gnome shell version 3.28 or 3.30 I will
look into doing a timeout. 

I think you are asking for an interval timeout. A timeout user
preference could be provided settable in hours and minutes. At
startup if the extension state is busy the timer would start or
if the state is set to busy by the user the timer would start.
The timer would be stopped if the state changed from busy to
available.  If the timer expires the state would be changed
from busy to available by the extension.

If this is what you want let me know. If so I will look at the
code this weekend.  I don't expect it to be very difficult.

**Comment by nls1729** [comment]
@bostrt 
I have most of the code written.  If I can find time it should be done by the end of the week. The review queue on extensions.gnome.org is very long and no extensions have been reviewed in weeks. I will provide you a zip file when I have it working if you don't mind running un-reviewed code.

**Comment by nls1729** [comment]
@bostrt 

The following attached file describes the Busy State Timeout Feature.
[description.txt](https://github.com/nls1729/acme-code/files/2873397/description.txt)

The zip file contains the extension.
[donotdisturb-button@nls1729.zip](https://github.com/nls1729/acme-code/files/2873402/donotdisturb-button%40nls1729.zip)

If you have any questions or find any bugs please comment here.
Let me know how it goes.

**Comment by bostrt** [comment]
@nls1729 just tested and works for me!

**Comment by nls1729** [comment]
@bostrt 
Closed.
