### ISSUE TITLE
Activities Configurator applies to login screen 

### ISSUE THREAD

**Issue by Jont828** [nls1729/acme-code#56]
The configurator applies on the login screen when the user shell theme isn't active. It overwrites the default gnome shell theme and replaces the panel background color and text. This happens when I suspend by closing my laptop lid and leave it like that, and it doesn't happen when I click the suspend button or simply lock the screen.

Is there any way to make it so it doesn't overwrite that or keep the original login panel style?

**Comment by nls1729** [comment]
I do not have a laptop.  From your description of the problem it looks like the laptop suspend code is not handling creating a login screen correctly.  When a normal suspend is done power is saved by keeping the state of the software in memory and removing power from the display and drives.  There is no login screen when the power button is pressed to resume.  Apparently the laptop requires a login before restoring the session.  The resume code seems to be using the panel that was saved.  The extension only alters the panel during the extension enable of the login or restores the panel if the extension is disabled during the session.   I don't see any way the extension is actively causing what you are seeing.

**Comment by Jont828** [comment]
Thanks for the response! I'm not too sure what you mean, every time I resume I always have to log in. Normally, there's no activities button in the login screen, and once I've logged in, the extension loads. For some reason now, the extension attempts to load right when the log in screen pops up. Once I've logged in, disabling the extension doesn't make the activities button revert to it's old state. I can provide pictures if that would help.

Like you said, it might not be a problem with the extension, but this didn't happen before I updated to Gnome 3.32 and updated the extension as well, so I'm not sure where to start looking.

**Comment by nls1729** [comment]
@Jont828 
Do you use an external monitor?
What linux distribution and version do you use?
Did you upgrade your linux to go to GS 3.32?
Pictures would be helpful.

**Comment by Jont828** [comment]
I don't use a monitor, and I'm on Arch Linux with Gnome 3.32. I'll reply with pictures soon.

**Comment by Jont828** [comment]
Here are some [pictures](https://imgur.com/a/b8ScJsi) of what I mean. The Arch icon gets pushed next to the text when the resume/login glitch happens. In the picture with the clock and wallpaper, the activities button shouldn't be showing and the panel background should be transparent instead of black, which it gets from the Set Panel Background thing.

**Comment by nls1729** [comment]
@Jont828
 
You are using the AUR version of the extension.  It is possible you do not have the most recent version of the code or a damaged copy.

Please do the following:

Since you use Arch I am sure you are familiar with the command line.  The attached file ActivtiesConfig.txt  contains instructions to save the AUR version. The attached zip-file will replace it with the latest version.

The main difference between the original version of the extension and the AUR version is the text of the activities area and the icon.  You can use the extension preferences to set the icon and text of the extension after it is replaced. 

The latest version may fix your problem.

Let me know how it goes.  

[ActivitiesConfig.txt](https://github.com/nls1729/acme-code/files/3116722/ActivitiesConfig.txt)


[activities-confignls1729.v73.shell-extension.zip](https://github.com/nls1729/acme-code/files/3116718/activities-confignls1729.v73.shell-extension.zip)

**Comment by nls1729** [comment]
@Jont828 

I may have found a problem.  Please try installing the attached zip file instead of the one in the previous comment.

[activities-config@nls1729.zip](https://github.com/nls1729/acme-code/files/3123863/activities-config%40nls1729.zip)

**Comment by nls1729** [comment]
@Jont828 

I assume this issue is resolved.  If the problem has not been cleared please let me know.
