### ISSUE TITLE
Activities Configurator Drop Shadow

### ISSUE THREAD

**Issue by jcuenod** [nls1729/acme-code#6]
It would be great to be able to control (1) the colour and (2) the presence of a drop shadow using this extension.

**Comment by nls1729** [comment]
Currently I am very busy and don't have any free time to modify extensions.  It will probably be two or three months before my free time returns.  The change you suggested is fairly simple to execute but involves more coding to add to the preferences UI than to the main part of the extension. With that said, you can make a simple change to the extension.js to get the shadow. For an explanation of the CSS element that you will add to the code see:
http://www.w3schools.com/cssref/css3_pr_box-shadow.asp

To edit the extension.js file:

Find the line "let backgroundStyle =".

The original code will be:
let backgroundStyle = 'background-color: rgba(' + colorString + ',' + this._panelOpacity.toString() + ')';

Change it to:
let backgroundStyle = 'background-color: rgba(' + colorString + ',' + this._panelOpacity.toString() + ')' + '; box-shadow: 0px 10px 20px rgba(0,0,0,0.9);';
For a black shadow.
OR
let backgroundStyle = 'background-color: rgba(' + colorString + ',' + this._panelOpacity.toString() + ')' + '; box-shadow: 0px 10px 20px rgba(255,255,255,0.9);';
For a white shadow.
You can use a program like Gcolor2 to find the rgba values you might want to use.

Please note the extension's Transparency setting should be 0 or very low since the alpha setting of the background will affect the shadow box alpha.
You can experiment to get the appearance you want.

I will leave this issue open until I have time to deal with it completely.
I hope this information will be useful to you.
Let me know how it goes.

**Comment by jcuenod** [comment]
Thanks, if I have time I will fork and put together a pull request but that doesn't look promising in the next month.

**Comment by nls1729** [comment]
I needed a break so I found a few hours over the weekend to work on the shadow feature.  I have some translations to do to finish it.  I should complete it this weekend.  The shadow will have the following configurable settings: color, transparency, vertical length, blur radius and spread radius. It turned out to look pretty good.

**Comment by jcuenod** [comment]
Great to hear. Thanks for your work on this!

> On Feb 23 2016, at 2:35 pm, Norman L. Smith &lt;notifications@github.com&gt;
wrote:  

>

> I needed a break so I found a few hours over the weekend to work on the
shadow feature. I have some translations to do to finish it. I should complete
it this weekend. The shadow will have the following configurable settings:
color, transparency, vertical length, blur radius and spread radius. It turned
out to look pretty good.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nls1729
/acme-code/issues/6#issuecomment-187890791).![](https://github.com/notificatio
ns/beacon/AEDovBTWbWXLqm63Ws9cSLiXklYqQF7Xks5pnLn4gaJpZM4Hbhth.gif)

**Comment by nls1729** [comment]
[activities-config@nls1729.zip](https://github.com/nls1729/acme-code/files/146999/activities-config.nls1729.zip)

Attached is a zip file you can install and try out.  If you find it acceptable I will push it to here and upload a it to the Gnome Shell Extension website.

**Comment by jcuenod** [comment]
This looks great.

One thing though is that when you change the colour, the transparency is reset
to 0.

> On Feb 25 2016, at 11:25 am, Norman L. Smith
&lt;notifications@github.com&gt; wrote:  

>

> [activities-config@nls1729.zip](https://github.com/nls1729/acme-
code/files/146999/activities-config.nls1729.zip)

>

> Attached is a zip file you can install and try out. If you find it
acceptable I will push it to here and upload a it to the Gnome Shell Extension
website.

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nls1729
/acme-code/issues/6#issuecomment-188889768).![](https://github.com/notificatio
ns/beacon/AEDovKId3SXiCq2g7W1GD6-2LofaqrNrks5pnzBwgaJpZM4Hbhth.gif)

**Comment by nls1729** [comment]
I changed the preferences to not set the transparency to 0 for both the panel background and the shadow on color change.  

I found some very ugly results with the interaction of the shadow and the max window effect. If a window is maximized when no max window effect is enabled the shadow remains and looks OK.  If the background changes color to opaque black or if the background has transparency and changes to opaque the shadow is affected. It becomes too intense and looks bad on the top of the maximized window.  I changed it to remove the shadow while an opaque max window effect is applied. Take a look at the attached.  Let me know how it goes.

[activities-config@nls1729.zip](https://github.com/nls1729/acme-code/files/148897/activities-config.nls1729.zip)

**Comment by jcuenod** [comment]
Okay, I'm using this extension in conjunction with "Hide Top Bar" and I've
modified my theme to do kind what Maximus used to do (in other words my
maximized windows look different and the top bar is hidden by default when I
maximize them). I'll give it a go though. Thanks.

> On Feb 26 2016, at 2:53 pm, Norman L. Smith &lt;notifications@github.com&gt;
wrote:  

>

> I changed the preferences to not set the transparency to 0 for both the
panel background and the shadow on color change.

>

> I found some very ugly results with the interaction of the shadow and the
max window effect. If a window is maximized when no max window effect is
enabled the shadow remains and looks OK. If the background changes color to
opaque black or if the background has transparency and changes to opaque the
shadow is affected. It becomes too intense and looks bad on the top of the
maximized window. I changed it to remove the shadow while an opaque max window
effect is applied. Take a look at the attached. Let me know how it goes.

>

> [activities-config@nls1729.zip](https://github.com/nls1729/acme-
code/files/148897/activities-config.nls1729.zip)

>

> —  
Reply to this email directly or [view it on GitHub](https://github.com/nls1729
/acme-code/issues/6#issuecomment-189479641).![](https://github.com/notificatio
ns/beacon/AEDovIyfNn14nWTzzudQFxd7JE6GgLPhks5poLLMgaJpZM4Hbhth.gif)

**Comment by nls1729** [comment]
I am closing this issue.  Let me know if all is not well.
