### ISSUE TITLE
Do not disturb doesn't hide notifications

### ISSUE THREAD

**Issue by mathsen** [nls1729/acme-code#68]
If I enable do not disturb mode messages of the "signal-desktop" app are neverthless shown and my journal is cluttered with messages like:

```
Jan 21 09:49:59 gnome-shell[1507]: Object St.Icon (0x55f2eecf2cb0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from>
Jan 21 09:49:59 gnome-shell[1507]: == Stack trace for context 0x55f2ded2b550 ==
Jan 21 09:49:59 gnome-shell[1507]: #0   55f2e3f95620 i   ~/.local/share/gnome-shell/extensions/donotdisturb-button@nls1729/dndBtnGObject.js:196 (7f2adb842430 @ 22)
Jan 21 09:49:59 gnome-shell[1507]: #1   55f2e3f95580 i   ~/.local/share/gnome-shell/extensions/donotdisturb-button@nls1729/dndBtnGObject.js:72 (7f2adb83de50 @ 148)
Jan 21 09:49:59 gnome-shell[1507]: #2   7ffca8142b20 I   resource:///org/gnome/gjs/modules/signals.js:135 (7f2ae11c6040 @ 376)
Jan 21 09:49:59 gnome-shell[1507]: #3   55f2e3f954e0 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:169 (7f2ae11d3e50 @ 39)
Jan 21 09:49:59 gnome-shell[1507]: == Stack trace for context 0x55f2ded2b550 ==
Jan 21 09:49:59 gnome-shell[1507]: #0   55f2e3f95620 i   ~/.local/share/gnome-shell/extensions/donotdisturb-button@nls1729/dndBtnGObject.js:197 (7f2adb842430 @ 42)
Jan 21 09:49:59 gnome-shell[1507]: #1   55f2e3f95580 i   ~/.local/share/gnome-shell/extensions/donotdisturb-button@nls1729/dndBtnGObject.js:72 (7f2adb83de50 @ 148)
Jan 21 09:49:59 gnome-shell[1507]: #2   7ffca8142b20 I   resource:///org/gnome/gjs/modules/signals.js:135 (7f2ae11c6040 @ 376)
Jan 21 09:49:59 gnome-shell[1507]: #3   55f2e3f954e0 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:169 (7f2ae11d3e50 @ 39)
Jan 21 09:49:59 gnome-shell[1507]: == Stack trace for context 0x55f2ded2b550 ==
Jan 21 09:49:59 gnome-shell[1507]: clutter_actor_hide: assertion 'CLUTTER_IS_ACTOR (self)' failed
Jan 21 09:49:59 gnome-shell[1507]: #0   55f2e3f95620 i   ~/.local/share/gnome-shell/extensions/donotdisturb-button@nls1729/dndBtnGObject.js:203 (7f2adb842430 @ 135)
Jan 21 09:49:59 gnome-shell[1507]: #1   55f2e3f95580 i   ~/.local/share/gnome-shell/extensions/donotdisturb-button@nls1729/dndBtnGObject.js:72 (7f2adb83de50 @ 148)
Jan 21 09:49:59 gnome-shell[1507]: #2   7ffca8142b20 I   resource:///org/gnome/gjs/modules/signals.js:135 (7f2ae11c6040 @ 376)
Jan 21 09:49:59 gnome-shell[1507]: #3   55f2e3f954e0 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:169 (7f2ae11d3e50 @ 39)
Jan 21 09:49:59 gnome-shell[1507]: Object St.Icon (0x55f2eecdb0b0), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from>
Jan 21 09:49:59 gnome-shell[1507]: clutter_actor_hide: assertion 'CLUTTER_IS_ACTOR (self)' failed
```
I use gnome 3.34.2 with "v34 GS 3.34" version of the extension.

**Comment by nls1729** [comment]
Has the extension and the signal-desktop app ever worked together properly?

If the extension and the app have worked properly when did it stop and was there any kind of
an update associated with the event?

**Comment by mathsen** [comment]
Yes, it worked until I would say 2 weeks ago... but to be honest I really don't know the exact cause, I do updates on a regular basis and at least there was no bigger signal update

**Comment by nls1729** [comment]
The last update to the extension was made available on September 29, 2019, version 34.  The messages in your report started showing up in my journal on December 1, 2019 after I upgraded to Fedora 31 with GS3.34.  

I found that gnome-shell was updated on January 10, 2020. 

Can you correlate the receipt of the notifications to the messages (ie.) the timestamp of the journal entries are at the time of the app's notification? 

Either something changed in the app or the gnome-shell since the extension changes were made in September of 2019.  

When did you update to gnome-shell 3.34? 

What linux distribution are you using? 

I will try to find what is causing the journal messages.  They appear on my system some days and on other days not at all.  That is strange.

**Comment by nls1729** [comment]
I have found the cause of the messages you reported.  I don't think they are associated with your problem with the "signal-desktop" app.  If you agree I will provide you a zip file  you can install with the message problem corrected.  It is possible it could fix your app problem but almost everything is possible.

**Comment by mathsen** [comment]
Excuse my late reply, of course I can test the new version if you send it to me.

**Comment by nls1729** [comment]
You can install it at:

https://extensions.gnome.org/extension/964/do-not-disturb-button/

It was ony a one line addition to the code so I uploaded to extensions.gnome.org.
It will be version 35.

**Comment by mathsen** [comment]
Thanks and the journal messages are indeed gone now!
Unfortunately signal messages still appear as notification, even in do not disturb mode... as a workaround I disabled notifications for signal completely in the gnome control center. Not a good solution, but better than the pop up windows...

**Comment by nls1729** [comment]
Since the extension worked in the past, I suspect  the app has changed or the app has not been updated for the latest changes in the gnome shell.  The only way a notification is displayed when the extension is in busy mode is for the notification to have a priority of "critical".  Since you can disable the notifications with the control center, I think the problem is in the app.  When gnome shell 3.34 was  released I had to make changes to the extension because of some basic changes in the shell.
