### ISSUE TITLE
GNOME 3.36 compatibility for activities-config

### ISSUE THREAD

**Issue by v4rakh** [nls1729/acme-code#70]
Hi,

thanks for writing this extension. I think we'd gladly appreciate an updated version which works with the latest GNOME 3.36 release.

**Comment by nls1729** [comment]
I am working on it.  What linux distribution are you using?

**Comment by v4rakh** [comment]
I am using ArchLinux (btw ^^).

**Comment by nls1729** [comment]
I think I can have the extension in working order by the weekend.  Would like a pre-release version to test?

**Comment by xTeixeira** [comment]
If you need anyone to test it I can help.

**Comment by v4rakh** [comment]
@nls1729 Sure, I'd volunteer for that. :+1:

**Comment by nls1729** [comment]
There were major changes to the extension.  This version of the extension  will only work with GS 3.36 (and hopefully later versions.)

I have uploaded a sha256sum check sum file named CHECKSUM and 
a zipfile named activities-config-20072142947 @ nls1729.zip.
space@space to prevent this site from making a link out of the filename...
The files are on my Google Drive.  You can download the files with the tiny url  links:

A Download button is at the top right side of the webpage.

https://tinyurl.com/checksum-for-zipfile

https://tinyurl.com/zipfile-activities-config

You may see a Woops on the zipfile.  It's not a problem.

$ cd Downloads
$ sha256sum -c CHECKSUM
activities-config-20072142947 @ nls1729.zip: OK
Install in directory ~/.local/share/gnome-shell/extensions/activities-config@nls1729
If old extension files are there remove them.

$ cd ~/.local/share/gnome-shell/extensions/activities-config@nls1729

Be sure you are WHERE you should be before you do the remove.
$ pwd
/home/boogieman/.local/share/gnome-shell/extensions/activities-config@nls1729

$ rm -rf *
$ ls
$ unzip ~/Downloads/activities-config-20072142947@nls1729.zip

Log out and login.

You should have an installed extension to test.
Let me know how it goes.

Thanks for your help.

**Comment by xTeixeira** [comment]
All the features and configs I use are now working fine.

I tested a few other features and I found enabling icon + activities text results in a visual glitch (I also testes with default shell theme and it's the same):
![Screenshot from 2020-03-13 17-45-28](https://user-images.githubusercontent.com/7085361/76658241-6ede2f80-6552-11ea-873c-b164a5cd89ea.png)

Other than that it seems fine to me.

**Comment by nls1729** [comment]
@xTeixeira I missed a needed alignment. In my testing  I used a larger font that hid the problem.  When I set the font to the normal size it was very obvious something was wrong. All centered now.  Thanks.

**Comment by v4rakh** [comment]
Is there a reason why we cannot build from a separate git branch? Would be easier and you could also reference this issue then. I am asking because I don't see any changes in the git repository for it. :-)

**Comment by nls1729** [comment]
@v4rakh 
I don't push branches to Github.  I use branches locally. When I complete a new version of an extension I submit it to extensions.gnome.org.  When ego accepts the extension it becomes available on the ego website with a new "official" version number. I then merge the local branch and push master to Github.  Some linux distributions use ego as an upstream source of extensions.  Fedora provides an optional package of the Activities Configurator as a "system" extension which is installed in /usr/share/gnome-shell/extensions.  I think Arch linux actually repackages an Arch branded version of the Activities Configurator.  I have had problems in the past where an extension would get "modified" and then go  a website as "freeware".  A freeware user would want me to fix their freeware.  I have a simple answer to those requests.  Go to the ego website and install the official version.  I do accept bug fixes and  enhancements from Github users who fork my repo and submit a merge request.  And finally to maintain the extension creation process I have a some ugly  tools that are needed to create the finished zip file of an extension.  Take a look at the Makefile for the Activities Configurator.  It uses a lot of resources that I don't push to Github and aren't in my local git repository.  If I were working as one developer in a group those tools would likely be maintained by one of the developers for use by the group.  In the early days of the Gnome Shell with the advent of shell extensions it was discussed how extensions should be handled.  Since an extension is actually a patch to the shell itself it was accepted  a member of the Gnome  group should review all extensions before being  released to the general public.  I agree with the need for review.  Before it is released to everyone my extensions get reviewed.  Sorry for the long winded response but it is kind of complicated.

**Comment by v4rakh** [comment]
If one likes to contribute, that's more difficult then without knowing your _real_ current state, but your decision anyway. 👍 

Will you publish the extension soon on ego? I'd close this issue then.

**Comment by nls1729** [comment]
Yes, I will upload later today.  Please leave this issue open.  Usually it takes a few days for the review to complete.  Leave the issue open.  When the extension is available on ego I will close the issue.

**Comment by nls1729** [comment]
Version 80 for GS 3.36 :
https://extensions.gnome.org/extension/358/activities-configurator/
