### ISSUE TITLE
Question - remove extensions 

### ISSUE THREAD

**Issue by yuriw** [nls1729/acme-code#72]
I see some extensions show Error and some show "Initialized"

This is a question and possible feature request. 

How to remove them ?
I tried some ways and still was not able to do so.
It'd be cool if this app would allow in addition to restarting - remove them.

**Comment by nls1729** [comment]
The Gnome Shell Extension Reloader is a tool intended for use by extension writers.  Depending on which linux distribution you use extensions can be installed from different sources.   There is a very simple way to remove an extension.  Remove the extension's directory and its contents.  There are two types of extensions, System (also known as Built-In) and User (also known as Manually Installed).  There are two locations where extensions are installed.  The System extensions are installed in /usr/share/gnome-shell/extensions.  The User extensions are installed in the user's home directory in .local/share/gnome-shell/extensions.  The same extension can be installed in both of the extension directories (and can be of different versions).  When the same extension is in both directories the User extension is the extension initialized when the gnome shell session starts. If the extension is functional and not enabled it will remain in the initialized state.  If the extension is functional and enabled it will be set to the enabled state.  If the extension is not functional it will set to the error state.  There is an important difference between System and User extensions.  System extensions are owned by root and User extensions are owned by the user. The Gnome Shell Extension Reloader could not remove a System extension because it is owned by root.  If you see extensions in the error state it can be due to an update to the gnome shell or a conflict with another installed extension.  A gnome shell extension is actually a "patch" to the shell.  Often if the shell changes an installed extension may require an update.  If two extensions patch the same code the conflict can cause an error. If a user extension is available on extensions.gnome.org it can be easily removed at extensions.gnome.org.  To remove a System extension remove the directory in /usr/share/gnome-shell/extensions.  It may not stay removed depending on its source.  Several System extensions are maintained by the gnome shell developers and are part of the linux distribution as System extensions.  Some linux distributions package and distribute System extensions from extensions.gnome.org.  The Gnome Shell Extension Reloader will remain as is.  Let me know if I have answered your question.

**Comment by yuriw** [comment]
@nls1729 thanks a lot, I removed extensions with errors

I still feel that with all info you could consider adding this to the app

**Comment by nls1729** [comment]
You might find the gse-zip-tool useful.  It will delete extensions and install extensions from a zip file.
It is a simple python program.  You can download the zip at the following:

https://github.com/nls1729/gse-zip-tool

Be sure to read the README.txt first.

You can make and install it in five minutes.

**Comment by yuriw** [comment]
@nls1729 would you recommend removing extensions in initialized state ?

**Comment by nls1729** [comment]
They don't take up very much disk space and some are useful if you want to take advantage of the feature they provide.  I  use User Themes for testing but don't leave it enbled.  Depending on your linux distribution you may find that if you remove some extensions they will reappear when the package that provides them has an update.  I don't think there is any advantage to removing them.
